#!/bin/sh

pull(){
	sudo docker pull mackerel/graphite
}

build(){
	mkdir -p ~/.grmwl/$1
	mkdir -p ~/.grmwl/$1/log
	mkdir -p ~/.grmwl/$1/whisper
	touch ~/.grmwl/$1/id	
        cp collectd.conf ~/.grmwl/$1/collectd.conf
	cp local_settings.py ~/.grmwl/$1/local_settings.py
	tmp=`sudo docker run -d --name $1 -v ~/.grmwl/$1/log:/var/log/graphite -v ~/.grmwl/$1/whisper:/var/lib/graphite/storage/whisper -v ~/.grmwl/$1/local_settings.py:/var/lib/graphite/lib/graphite/local_settings.py -p 8000:8000 -p 2003:2003 -p 2004:2004 mackerel/graphite`
	echo $tmp > ~/.grmwl/$1/id
}

install_collectd(){
	git submodule init
	git submodule update
	sudo apt-get install libmnl-dev libcurl4-gnutls-dev librtmp-dev libgnutls-dev libgcrypt11-dev
	cd collectd && ./build.sh 1>/dev/null && ./configure 1>/dev/null && sudo make && sudo make install
}

install_docker(){
	sudo apt-get install docker
	sudo apt-get install docker.io
}

start(){
	sudo /opt/collectd/sbin/collectd -C ~/.grmwl/$1/collectd.conf
	sudo docker start `cat ~/.grmwl/$1/id`
	echo "[+] Open your browser and go to http://localhost:8000/ to open Graphite UI."
}

stop(){
	ps xa -o pid,cmd | grep "/opt/collectd/sbin/collectd -C ~/.grmwl/$1/collectd.conf" | cut -c 1- | cut -d\  -f 1 | xargs --no-run-if-empty sudo kill
	sudo docker stop `cat ~/.grmwl/$1/id`
}

clean_container(){
	sudo docker ps -a --no-trunc | grep `cat ~/.grmwl/$1/id` | awk '{print $1}' | xargs --no-run-if-empty sudo docker rm -f
}

if [ "$1" = "init" ]; then
	install_collectd
	install_docker	
elif [ "$1" = "list" ]; then
	for i in $(ls ~/.grmwl); do 
                if sudo docker ps --no-trunc | grep `cat ~/.grmwl/$i/id` 2>&1 >/dev/null; then
			echo "[+] $i - running"
		else
			echo "[+] $i - stopped"
		fi
	done
elif [ "$1" = "create" ]; then
	if [ -x ~/.grmwl/$2/id ]; then
		echo "[!] Project already created."
	else
		echo "[+] Creating project $2..."
		pull
		build $2
	fi
	
elif [ "$1" = "start" ]; then
	if [ -x ~/.grmwl/$2/id ]; then
		echo "[!] Project does not exist, you need to create it first ($0 create $2)"
	else
		if sudo docker ps --no-trunc | grep `cat ~/.grmwl/$2/id` 2>&1 >/dev/null; then
			echo "[!] Project $2 is already running."
		else	
			echo "[+] Running project $2..."
			start $2
		fi
	fi
elif [ "$1" = "stop" ]; then
	if [ -x ~/.grmwl/$2/id ]; then
		echo "[!] Project does not exist, you need to create it first ($0 create $2)"
	else
		echo "[+] Stopping project $2..."
		stop $2
	fi
elif [ "$1" = "restart" ]; then
	stop $2
	start $2
elif [ "$1" = "delete" ]; then
	if [ -x ~/.grmwl/$2/id ]; then
		echo "[!] Project $2 does not exist."
	else
		echo "[+] Deleting project $2..."
		clean_container $2
		sudo rm ~/.grmwl/$2 -R
	fi
else
	echo "Usage : {init, list, create,run,delete} [project]"
fi

