#!/bin/sh

pull(){
	sudo docker pull mackerel/graphite
}

build(){
	mkdir -p ~/.grmwl/$1
	mkdir -p ~/.grmwl/$1/log
	mkdir -p ~/.grmwl/$1/whisper
	touch ~/.grmwl/$1/id	
	tmp=`sudo docker run -d --name $1 -v ~/.grmwl/$1/log:/var/log/graphite -v ~/.grmwl/$1/whisper:/var/lib/graphite/storage/whisper -v /etc/localtime:/etc/localtime:ro -p 8000:8000 -p 2003:2003 -p 2004:2004 mackerel/graphite`
	echo $tmp > ~/.grmwl/$1/id
	cp collectd.conf ~/.grmwl/$1/collectd.conf
}
run(){
	sudo service collectd stop
	sudo collectd -C ~/.grmwl/$1/collectd.conf
	sudo docker start `cat ~/.grmwl/$1/id`
	echo "Open your browser and go to http://localhost:8000/ to open Graphite UI."
}

stop(){
	sudo docker stop `cat ~/.grmwl/$1/id`
}

clean_container(){
	sudo docker ps -a | grep `cat ~/.grmwl/$1/id` | awk '{print $1}' | xargs --no-run-if-empty sudo docker rm -f
}


if which collectd 2>&1 >/dev/null; then
	if [ "$1" = "create" ]; then
		if [ -x ~/.grmwl/$2/id ]; then
			echo "Project already created."
		else
			echo "Creating project $2..."
			pull
			build $2
		fi

	elif [ "$1" = "run" ]; then
		if [ -x ~/.grmwl/$2/id ]; then
			echo "Project does not exist, you need to create it first ($0 create $2)"
		else
			echo "Running project $2..."
			run $2
		fi
	elif [ "$1" = "stop" ]; then
		if [ -x ~/.grmwl/$2/id ]; then
			echo "Project does not exist, you need to create it first ($0 create $2)"
		else
			echo "Stopping project $2..."
			stop $2
		fi
	elif [ "$1" = "delete" ]; then
		if [ -x ~/.grmwl/$2/id ]; then
			echo "Project $2 does not exist."
		else
			echo "Deleting project $2..."
			clean_container $2
			rm ~/.grmwl/$2 -R
		fi
	else
		echo "Usage : (create,run,delete) project"
	fi
else
	echo "collectd is no installed."
fi
